from app.models import (
    AgentRun,
    AgentStep,
    ApprovalEvent,
    ApprovalRequest,
    AttendanceRecord,
    AuditLog,
    Candidate,
    Department,
    Designation,
    Employee,
    EmployeeAsset,
    EmployeeDocument,
    LeaveApproval,
    LeaveBalance,
    LeaveRequest,
    LeaveType,
    LookupValue,
    Notification,
    PayrollRun,
    PayrollRunItem,
    EmployeeSalaryAssignment,
    SalaryAssignmentApproval,
    SalaryRevisionHistory,
    SalaryComponent,
    SalaryStructure,
    SalaryStructureItem,
    Permission,
    RefreshToken,
    Role,
    RolePermission,
    User,
    UserRole,
)
from app.models.auth.models import FaceLoginAttempt  # noqa: F401
from app.models.auth.models import ActivationToken  # noqa: F401  (NEW)
from app.models.employee.models import OffboardingCase  # noqa: F401  (NEW)
from app.models.knowledge.models import KnowledgeChunk  # noqa: F401  (NEW)
from app.models.knowledge.models import KnowledgeChatMessage  # noqa: F401  (NEW)
from app.models.base import Base

__all__ = [
    "AgentRun",
    "AgentStep",
    "ApprovalRequest",
    "ApprovalEvent",
    "AttendanceRecord",
    "AuditLog",
    "Base",
    "Candidate",
    "Department",
    "Designation",
    "Employee",
    "EmployeeAsset",
    "EmployeeDocument",
    "LeaveApproval",
    "LeaveBalance",
    "LeaveRequest",
    "LeaveType",
    "LookupValue",
    "Notification",
    "PayrollRun",
    "PayrollRunItem",
    "EmployeeSalaryAssignment",
    "SalaryAssignmentApproval",
    "SalaryRevisionHistory",
    "SalaryComponent",
    "SalaryStructure",
    "SalaryStructureItem",
    "Permission",
    "RefreshToken",
    "Role",
    "RolePermission",
    "User",
    "UserRole",
    "FaceLoginAttempt",
    "ActivationToken",
    "OffboardingCase",
    "KnowledgeChunk",
    "KnowledgeChatMessage",
]