"""Add vpf_amount to employees

Revision ID: bca369fa44ae
Revises: 20260802_0038
Create Date: 2026-08-10 11:40:30.407071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca369fa44ae'
down_revision: Union[str, None] = '20260802_0038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_conv_messages_session_created', table_name='conversation_messages')
    op.create_index(op.f('ix_conversation_messages_deleted_at'), 'conversation_messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_tenant_id'), 'conversation_messages', ['tenant_id'], unique=False)
    op.alter_column('conversation_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_conv_sessions_expires', table_name='conversation_sessions')
    op.drop_index('uq_conv_session_user_active', table_name='conversation_sessions', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_conversation_sessions_deleted_at'), 'conversation_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_tenant_id'), 'conversation_sessions', ['tenant_id'], unique=False)
    op.add_column('employees', sa.Column('vpf_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'vpf_amount')
    op.drop_index(op.f('ix_conversation_sessions_tenant_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_deleted_at'), table_name='conversation_sessions')
    op.create_index('uq_conv_session_user_active', 'conversation_sessions', ['user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index('ix_conv_sessions_expires', 'conversation_sessions', ['expires_at'], unique=False)
    op.alter_column('conversation_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_sessions', 'last_activity_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_conversation_messages_tenant_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_deleted_at'), table_name='conversation_messages')
    op.create_index('ix_conv_messages_session_created', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.alter_column('conversation_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversation_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
