"""add extended offboarding fields

Revision ID: 4b49910ef58f
Revises: b3bf5c4988d0
Create Date: 2026-08-31 16:03:08.097334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b49910ef58f'
down_revision: Union[str, None] = 'b3bf5c4988d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offboarding_cases', sa.Column('nda_signed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('offboarding_cases', sa.Column('client_credentials_cleared', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('offboarding_cases', sa.Column('personal_logins_cleared', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('offboarding_cases', sa.Column('recovery_details_updated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offboarding_cases', 'recovery_details_updated')
    op.drop_column('offboarding_cases', 'personal_logins_cleared')
    op.drop_column('offboarding_cases', 'client_credentials_cleared')
    op.drop_column('offboarding_cases', 'nda_signed')
    # ### end Alembic commands ###
