"""Add EmployeeOffer model

Revision ID: 5da112e18f7f
Revises: e1f2e34da356
Create Date: 2026-08-25 15:42:51.690490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da112e18f7f'
down_revision: Union[str, None] = 'e1f2e34da356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_offers',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_offers_deleted_at'), 'employee_offers', ['deleted_at'], unique=False)
    op.create_index('ix_employee_offers_employee_id', 'employee_offers', ['employee_id'], unique=False)
    op.create_index('ix_employee_offers_status', 'employee_offers', ['status'], unique=False)
    op.create_index(op.f('ix_employee_offers_tenant_id'), 'employee_offers', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_offers_tenant_id'), table_name='employee_offers')
    op.drop_index('ix_employee_offers_status', table_name='employee_offers')
    op.drop_index('ix_employee_offers_employee_id', table_name='employee_offers')
    op.drop_index(op.f('ix_employee_offers_deleted_at'), table_name='employee_offers')
    op.drop_table('employee_offers')
    # ### end Alembic commands ###
