"""move face biometrics to users

Revision ID: 68d80aa26abe
Revises: 20260821_0039
Create Date: 2026-08-21 19:31:56.198303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d80aa26abe'
down_revision: Union[str, None] = '20260821_0039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'face_samples_count')
    op.drop_column('employees', 'face_embedding')
    op.drop_column('employees', 'face_registered')
    op.add_column('face_login_attempts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index('ix_face_login_attempts_employee_id', table_name='face_login_attempts')
    op.create_index('ix_face_login_attempts_user_id', 'face_login_attempts', ['user_id'], unique=False)
    op.drop_constraint('face_login_attempts_employee_id_fkey', 'face_login_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'face_login_attempts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('face_login_attempts', 'employee_id')
    op.add_column('users', sa.Column('face_embedding', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('face_registered', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('face_samples_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_samples_count')
    op.drop_column('users', 'face_registered')
    op.drop_column('users', 'face_embedding')
    op.add_column('face_login_attempts', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'face_login_attempts', type_='foreignkey')
    op.create_foreign_key('face_login_attempts_employee_id_fkey', 'face_login_attempts', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_face_login_attempts_user_id', table_name='face_login_attempts')
    op.create_index('ix_face_login_attempts_employee_id', 'face_login_attempts', ['employee_id'], unique=False)
    op.drop_column('face_login_attempts', 'user_id')
    op.add_column('employees', sa.Column('face_registered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('employees', sa.Column('face_embedding', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('face_samples_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
