"""make official_email required

Revision ID: 90e55b9592b8
Revises: 5da112e18f7f
Create Date: 2026-08-25 17:18:52.210364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e55b9592b8'
down_revision: Union[str, None] = '5da112e18f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'official_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'official_email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)
    # ### end Alembic commands ###
