"""add_face_auth_columns_and_table

Revision ID: a7ee3a56d3f3
Revises: d1e7576abdb4
Create Date: 2026-08-21 12:51:21.354305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ee3a56d3f3'
down_revision: Union[str, None] = 'd1e7576abdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_login_attempts',
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_login_attempts_deleted_at'), 'face_login_attempts', ['deleted_at'], unique=False)
    op.create_index('ix_face_login_attempts_employee_id', 'face_login_attempts', ['employee_id'], unique=False)
    op.create_index('ix_face_login_attempts_success', 'face_login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_face_login_attempts_tenant_id'), 'face_login_attempts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_login_attempts_tenant_id'), table_name='face_login_attempts')
    op.drop_index('ix_face_login_attempts_success', table_name='face_login_attempts')
    op.drop_index('ix_face_login_attempts_employee_id', table_name='face_login_attempts')
    op.drop_index(op.f('ix_face_login_attempts_deleted_at'), table_name='face_login_attempts')
    op.drop_table('face_login_attempts')
    # ### end Alembic commands ###
