"""add tenant_id to offboarding_cases

Revision ID: b3bf5c4988d0
Revises: 20260827_0043
Create Date: 2026-08-31 15:47:21.146048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3bf5c4988d0'
down_revision: Union[str, None] = '20260827_0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activation_tokens', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('activation_tokens', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_activation_tokens_deleted_at'), 'activation_tokens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activation_tokens_tenant_id'), 'activation_tokens', ['tenant_id'], unique=False)
    op.add_column('offboarding_cases', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('offboarding_cases', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_offboarding_cases_deleted_at'), 'offboarding_cases', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_offboarding_cases_tenant_id'), 'offboarding_cases', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offboarding_cases_tenant_id'), table_name='offboarding_cases')
    op.drop_index(op.f('ix_offboarding_cases_deleted_at'), table_name='offboarding_cases')
    op.drop_column('offboarding_cases', 'deleted_at')
    op.drop_column('offboarding_cases', 'tenant_id')
    op.drop_index(op.f('ix_activation_tokens_tenant_id'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_deleted_at'), table_name='activation_tokens')
    op.drop_column('activation_tokens', 'deleted_at')
    op.drop_column('activation_tokens', 'tenant_id')
    # ### end Alembic commands ###
