"""candidate offers

Revision ID: dff650c39874
Revises: 2eae6621d3ba
Create Date: 2026-09-02 11:08:36.280433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff650c39874'
down_revision: Union[str, None] = '2eae6621d3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_offers',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('offer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_offers_candidate_id', 'candidate_offers', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_offers_deleted_at'), 'candidate_offers', ['deleted_at'], unique=False)
    op.create_index('ix_candidate_offers_status', 'candidate_offers', ['status'], unique=False)
    op.create_index(op.f('ix_candidate_offers_tenant_id'), 'candidate_offers', ['tenant_id'], unique=False)
    op.drop_index('ix_employee_offers_deleted_at', table_name='employee_offers')
    op.drop_index('ix_employee_offers_employee_id', table_name='employee_offers')
    op.drop_index('ix_employee_offers_status', table_name='employee_offers')
    op.drop_index('ix_employee_offers_tenant_id', table_name='employee_offers')
    op.drop_table('employee_offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_offers',
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('offer_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_offers_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='employee_offers_pkey')
    )
    op.create_index('ix_employee_offers_tenant_id', 'employee_offers', ['tenant_id'], unique=False)
    op.create_index('ix_employee_offers_status', 'employee_offers', ['status'], unique=False)
    op.create_index('ix_employee_offers_employee_id', 'employee_offers', ['employee_id'], unique=False)
    op.create_index('ix_employee_offers_deleted_at', 'employee_offers', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_candidate_offers_tenant_id'), table_name='candidate_offers')
    op.drop_index('ix_candidate_offers_status', table_name='candidate_offers')
    op.drop_index(op.f('ix_candidate_offers_deleted_at'), table_name='candidate_offers')
    op.drop_index('ix_candidate_offers_candidate_id', table_name='candidate_offers')
    op.drop_table('candidate_offers')
    # ### end Alembic commands ###
