"""Add EmployeeRecord model

Revision ID: e1f2e34da356
Revises: 68d80aa26abe
Create Date: 2026-08-25 12:55:23.011461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f2e34da356'
down_revision: Union[str, None] = '68d80aa26abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_records',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_issued', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_records_deleted_at'), 'employee_records', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_records_tenant_id'), 'employee_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_records_tenant_id'), table_name='employee_records')
    op.drop_index(op.f('ix_employee_records_deleted_at'), table_name='employee_records')
    op.drop_table('employee_records')
    # ### end Alembic commands ###
